In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv('https://raw.githubusercontent.com/soaicbe/ml/master/spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
'''from gensim.parsing.preprocessing import remove_stopwords
import string

# Function to remove stop words and punctuation
def preprocess_text(text):
    text = remove_stopwords(text)
    # Remove punctuation using str.translate
    translation_table = str.maketrans("", "", string.punctuation)
    text = text.translate(translation_table)
    return text

# Apply preprocessing to each row in the 'Message' column
df['Message'] = df['Message'].apply(preprocess_text)

# Print the updated DataFrame
print(df)
'''

'from gensim.parsing.preprocessing import remove_stopwords\nimport string\n\n# Function to remove stop words and punctuation\ndef preprocess_text(text):\n    text = remove_stopwords(text)\n    # Remove punctuation using str.translate\n    translation_table = str.maketrans("", "", string.punctuation)\n    text = text.translate(translation_table)\n    return text\n\n# Apply preprocessing to each row in the \'Message\' column\ndf[\'Message\'] = df[\'Message\'].apply(preprocess_text)\n\n# Print the updated DataFrame\nprint(df)\n'

In [ ]:
df.Message

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [ ]:
df.Message.tolist()

In [ ]:
list(set("a a b a d c".split(' ')))

['b', 'a', 'd', 'c']

In [ ]:
df.Message = df.Message.str.lower()

In [ ]:
x_train = df.Message
y_train = df.Category

In [ ]:
y_train.map({'spam':True, 'ham':False})

0       False
1       False
2        True
3       False
4       False
        ...  
5567     True
5568    False
5569    False
5570    False
5571    False
Name: Category, Length: 5572, dtype: bool

In [ ]:
vocab = list(set([w for text in df.Message.tolist() for w in text.split(' ')]))
vocab_size = len(vocab)
print('%d unique words found' % vocab_size) # 18 unique words found
print(vocab)


13576 unique words found
['', 'snake.', 'credit!', 'loans', 'someplace,', 'too.pray', 'discuss', 'range', 'nokia,', 'payment', 'celebrate', 'gr8', "'married'", 'nights', 'annoyin!', 'cat', 'gal-no,', 'sum', 'question(std', 'me...ummifying...bye.', 'breaker', '09050000332', 'alone"', 'borin', 'likes', 'down:)', 'left.', 'chile,', 'textand', 'dat.', '83118', 'flat,', 'joking.,', 'scallies,', 'lancaster,', 'performed?', 'course...', 'gist', 'somewhere', 'couple', 'oni', 'closed.', 'spouse', 'txtno', 'party:-)', 'rummer.', 'ml', "hasn't,", '3-maruti', 'deepest', 'you.:)k:)where', 'pulls', 'band', 'mr.', 'statements', '(book', 'newest', 'practising', 'goal', 'waking', 'ages..ring', 'should', 'exactly.', 'disturbance.might', '£10,000', 'later..', '2stoptxt', 'to:', 'super', 'campus.', 'forms', 'pack', 'problem?', '08715203028', 'filthyguys.', '08709222922.', 'shake', 'diamonds.', 'in2', 'fine,', 'fringe', 'has,', '0906346330.', 'waheeda', 'sh', 'jocks', 'shuhui', 'us:)no', 'you/carlos', "4'o

In [ ]:
x_train = df.Message
y_train = df.Category

In [ ]:
#remove punctuation
def remove_punctuation(test_str):
  return test_str.translate(str.maketrans('','',string.punctuation))

In [ ]:
from gensim.parsing.preprocessing import remove_stopwords

# Apply remove_stopwords to each row in the 'Message' column
df['Message'] = df['Message'].apply(lambda x: remove_stopwords(x))

# Print the updated DataFrame
print(df)

     Category                                            Message
0         ham  jurong point, crazy.. available bugis n great ...
1         ham                      ok lar... joking wif u oni...
2        spam  free entry 2 wkly comp win fa cup final tkts 2...
3         ham                      u dun early hor... u c say...
4         ham                    nah don't think goes usf, lives
...       ...                                                ...
5567     spam  2nd time tried 2 contact u. u won £750 pound p...
5568      ham                       ü b going esplanade fr home?
5569      ham           pity, * mood that. so...any suggestions?
5570      ham  guy bitching acted like i'd interested buying ...
5571      ham                                         rofl. true

[5572 rows x 2 columns]


In [ ]:
# Assign indices to each word.
word_to_idx = { w: i for i, w in enumerate(vocab) }
idx_to_word = { i: w for i, w in enumerate(vocab) }
print(word_to_idx['good']) # 16 (this may change)
print(idx_to_word[0]) # sad (this may change)

3334



In [ ]:
idx_to_word

In [ ]:
import numpy as np

def createInputs(text):
  '''
  Returns an array of one-hot vectors representing the words
  in the input text string.
  - text is a string
  - Each one-hot vector has shape (vocab_size, 1)
  '''
  inputs = []
  for w in text.split(' '):
    v = np.zeros((vocab_size, 1))
    v[word_to_idx[w]] = 1
    inputs.append(v)
  return inputs

In [ ]:
createInputs("happy")

[array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]])]

In [ ]:
testip = "i am very happy"
for word, vec in zip(testip.split(" "), createInputs(testip)):
    print(word, vec.shape)

i (13576, 1)
am (13576, 1)
very (13576, 1)
happy (13576, 1)


In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
class RNN:
  # A Vanilla Recurrent Neural Network.

  def __init__(self, input_size, output_size, hidden_size=64):
    # Weights
    self.Whh = randn(hidden_size, hidden_size) / 1000
    self.Wxh = randn(hidden_size, input_size) / 1000
    self.Why = randn(output_size, hidden_size) / 1000

    # Biases
    self.bh = np.zeros((hidden_size, 1))
    self.by = np.zeros((output_size, 1))

  def forward(self, inputs):

    h = np.zeros((self.Whh.shape[0], 1))

    self.last_inputs = inputs
    self.last_hs = { 0: h }

    for i, x in enumerate(inputs):
      h = np.tanh(self.Wxh @ x + self.Whh @ h + self.bh)
      self.last_hs[i + 1] = h

    y = self.Why @ h + self.by
    return y, h

  def backprop(self, d_y, learn_rate=2e-2):
      '''
      Perform a backward pass of the RNN.
      - d_y (dL/dy) has shape (output_size, 1).
      - learn_rate is a float.
      '''
      n = len(self.last_inputs)

      # Calculate dL/dWhy and dL/dby.
      d_Why = d_y @ self.last_hs[n].T
      d_by = d_y

      # Initialize dL/dWhh, dL/dWxh, and dL/dbh to zero.
      d_Whh = np.zeros(self.Whh.shape)
      d_Wxh = np.zeros(self.Wxh.shape)
      d_bh = np.zeros(self.bh.shape)

      # Calculate dL/dh for the last h.
      d_h = self.Why.T @ d_y

      # Backpropagate through time.
      for t in reversed(range(n)):
        # An intermediate value: dL/dh * (1 - h^2)
        temp = ((1 - self.last_hs[t + 1] ** 2) * d_h)

        # dL/db = dL/dh * (1 - h^2)
        d_bh += temp

        # dL/dWhh = dL/dh * (1 - h^2) * h_{t-1}
        d_Whh += temp @ self.last_hs[t].T

        # dL/dWxh = dL/dh * (1 - h^2) * x
        d_Wxh += temp @ self.last_inputs[t].T

        # Next dL/dh = dL/dh * (1 - h^2) * Whh
        d_h = self.Whh @ temp

      # Clip to prevent exploding gradients.
      for d in [d_Wxh, d_Whh, d_Why, d_bh, d_by]:
        np.clip(d, -1, 1, out=d)

      # Update weights and biases using gradient descent.
      self.Whh -= learn_rate * d_Whh
      self.Wxh -= learn_rate * d_Wxh
      self.Why -= learn_rate * d_Why
      self.bh -= learn_rate * d_bh
      self.by -= learn_rate * d_by

In [ ]:
inputs = df.Message.tolist()
rnn = RNN(vocab_size, 2) # vocab_size is 18

In [ ]:
rnn.__dict__

{'Whh': array([[-1.32959039e-03, -8.06403996e-04,  7.91280771e-04, ...,
          5.58155859e-04, -7.82017842e-04,  4.31250950e-04],
        [-1.51484610e-03,  1.40624331e-03,  3.31313408e-04, ...,
         -1.32741450e-04, -9.22668389e-04, -2.31703188e-03],
        [-1.53342130e-04,  2.11558996e-04, -6.69256805e-04, ...,
         -9.02657964e-05,  8.91541868e-04,  4.15163505e-04],
        ...,
        [-9.59779647e-04, -1.24894368e-04,  1.31325879e-03, ...,
          4.28741588e-04, -7.26312057e-04, -3.43192928e-04],
        [ 9.36838009e-04,  9.17563774e-04,  3.55959390e-04, ...,
         -9.41198578e-05,  4.57717841e-04,  1.36657134e-03],
        [ 1.39388983e-04,  9.27084828e-04,  1.64302838e-03, ...,
          2.74558831e-04,  6.99364853e-04,  5.25791105e-04]]),
 'Wxh': array([[-9.21889360e-04,  7.03677980e-04, -1.52491153e-04, ...,
         -1.79974679e-03, -3.17706367e-04,  1.44053177e-03],
        [ 7.49489519e-04, -1.73402049e-03,  4.65117037e-04, ...,
         -2.55114956e-04

In [ ]:
inputs = createInputs("i am very happy")
inputs

[array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]])]

In [ ]:
def softmax(xs):
  # Applies the Softmax Function to the input array.
  return np.exp(xs) / sum(np.exp(xs))

In [ ]:
rnn.forward(inputs) # gives y and h

(array([[7.32861096e-06],
        [4.16061665e-06]]),
 array([[-1.28191631e-03],
        [-1.96379678e-03],
        [-8.26711712e-04],
        [ 1.26491480e-03],
        [-1.94320725e-03],
        [ 2.45076663e-04],
        [-1.13362728e-03],
        [ 5.22531154e-05],
        [ 4.35247252e-04],
        [ 1.34347615e-03],
        [ 3.21156855e-04],
        [ 1.26810250e-03],
        [ 7.29409789e-04],
        [-7.32686971e-04],
        [ 1.38503708e-03],
        [ 6.10027487e-04],
        [ 1.27909171e-03],
        [-5.59073186e-04],
        [ 1.11306495e-03],
        [-1.60571120e-05],
        [-4.64104636e-04],
        [ 5.42556733e-04],
        [-7.20584498e-04],
        [ 1.45242629e-03],
        [-1.59479078e-03],
        [ 1.25198800e-03],
        [-5.16735351e-04],
        [ 5.04528241e-04],
        [-1.63639402e-03],
        [ 7.05336622e-04],
        [ 6.39061761e-05],
        [-1.05340157e-03],
        [-2.03004383e-04],
        [ 9.09344916e-04],
        [ 1.02835340e-03],
 

In [ ]:
rnn.forward(inputs)[0] # y alone

array([[7.32861096e-06],
       [4.16061665e-06]])

In [ ]:
softmax(rnn.forward(inputs)[0])

array([[0.50000079],
       [0.49999921]])

In [ ]:
inputs = createInputs("i am happy")
softmax(rnn.forward(inputs)[0])

array([[0.50000079],
       [0.49999921]])

In [ ]:
# sad [1, 0]
# happy [0, 1]

In [ ]:
import random

def processData(x_train, y_train, backprop=True):
  '''
  Returns the RNN's loss and accuracy for the given data.
  - x_train: List of input data.
  - y_train: List of target labels.
  - backprop determines if the backward phase should be run.
  '''
  items = list(zip(x_train, y_train))  # Zip the input and target lists
  random.shuffle(items)

  loss = 0
  num_correct = 0

  for x, y in items:
    inputs = createInputs(x)
    target = int(y)

    # Forward
    out, _ = rnn.forward(inputs)
    probs = softmax(out)

    # Calculate loss / accuracy
    loss -= np.log(probs[target])
    num_correct += int(np.argmax(probs) == target)

    if backprop:
      # Build dL/dy
      d_L_d_y = probs
      d_L_d_y[target] -= 1

      # Backward
      rnn.backprop(d_L_d_y)

  return loss / len(items), num_correct / len(items)


In [ ]:
# Training loop
for epoch in range(1000):
    train_loss, train_acc = processData(x_train, y_train.map({'spam': True, 'ham': False}))

    if epoch % 100 == 99:
        print('--- Epoch %d' % (epoch + 1))
        print('Train:\tLoss %.3f | Accuracy: %.3f' % (train_loss, train_acc))

        test_loss, test_acc = processData(test_data, backprop=False)
        print('Test:\tLoss %.3f | Accuracy: %.3f' % (test_loss, test_acc))

In [ ]:
rnn.__dict__

In [ ]:
inputs = createInputs("i am happy")
out, _ = rnn.forward(inputs)
softmax(out)

In [ ]:
inputs = createInputs("i am sad")
out, _ = rnn.forward(inputs)
softmax(out)

In [ ]:
inputs = createInputs("i am great")
out, _ = rnn.forward(inputs)
softmax(out)

# Out of Vocab Word