In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.36023286, -0.33372724,  0.00410477,  0.6082134 , -0.68392366,
        -0.5553984 , -0.32838067,  0.5445516 , -0.4660766 ,  0.2992916 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.07151213, 0.07343294, 0.10294602, 0.18835215, 0.05173716,
        0.05883291, 0.07382661, 0.17673501, 0.06432983, 0.13829534]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2931 - accuracy: 0.9144
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1421 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1072 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0866 - accuracy: 0.9731
Epoch 5/5
 325/1875 [====>.........................] - ETA: 6s - loss: 0.0717 - accuracy: 0.9776

In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0784 - accuracy: 0.9744 - 488ms/epoch - 2ms/step


[0.07843077182769775, 0.974399983882904]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1459123e-07, 9.8627936e-08, 1.5335612e-05, 3.8691904e-04,
        3.0966998e-09, 9.0669226e-07, 1.5008122e-12, 9.9959093e-01,
        3.0463912e-07, 5.4162429e-06],
       [3.1331828e-07, 1.0346231e-05, 9.9995923e-01, 2.9304887e-05,
        1.5442807e-11, 7.3645808e-08, 5.5465085e-07, 1.3197443e-12,
        7.0498999e-08, 8.4428072e-12],
       [2.1437813e-07, 9.9899501e-01, 8.6151354e-05, 3.9930610e-06,
        3.5186811e-05, 1.2304610e-05, 6.0253449e-05, 7.3142350e-04,
        7.4985124e-05, 4.6477470e-07],
       [9.9644035e-01, 4.9248023e-09, 3.5132546e-04, 6.8860449e-05,
        8.2559325e-04, 4.5552800e-04, 1.8417103e-03, 9.2788623e-06,
        2.2942878e-07, 7.1205818e-06],
       [4.1483718e-06, 4.3816410e-08, 7.9613392e-06, 3.5780882e-08,
        9.9872762e-01, 1.4765424e-05, 6.1928949e-05, 1.2958947e-05,
        8.5593916e-07, 1.1695561e-03]], dtype=float32)>